# Generated by Django 6.0.4 on 2026-04-15 14:37

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name='AICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(help_text='MD5 hash of the prompt', max_length=64, unique=True)),
                ('response', models.JSONField(help_text='Cached AI response payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Soft expiry timestamp')),
            ],
            options={
                'db_table': 'ai_cache',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, default='Unknown', max_length=300)),
                ('rating', models.FloatField(blank=True, help_text='Rating out of 5.0', null=True)),
                ('num_reviews', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True)),
                ('book_url', models.URLField(max_length=1000, unique=True)),
                ('cover_image', models.URLField(blank=True, max_length=1000)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(blank=True, max_length=200)),
                ('sentiment', models.CharField(blank=True, help_text='Tone: Uplifting, Dark, Neutral, etc.', max_length=100)),
                ('summary', models.TextField(blank=True, help_text='AI-generated book summary')),
                ('recommendations', models.JSONField(blank=True, default=list, help_text='List of recommended book titles')),
                ('processed', models.BooleanField(default=False, help_text='True once AI insights and embeddings are generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('sources', models.JSONField(default=list, help_text='List of {book_id, book_title, chunk_index, relevance_score}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.IntegerField(help_text='Position in the sequence of chunks')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, help_text='768-dim vector from Gemini text-embedding-004', null=True)),
                ('embedding_id', models.CharField(blank=True, help_text='ChromaDB document ID for this chunk', max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='bookapp.book')),
            ],
            options={
                'db_table': 'book_chunks',
                'ordering': ['chunk_index'],
                'unique_together': {('book', 'chunk_index')},
            },
        ),
    ]
