# Generated by Django 6.0.4 on 2026-04-15 15:56

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, help_text='3072-dim vector from Gemini', null=True),
        ),
    ]
